from django.urls import path
from .views import (
    UserRegistrationView, OnboardingView,
    UserLoginView, LogoutView,
    AccountInfoView, PersonalInfoView,
    ChangePasswordView,Setup2FAView, Verify2FAView, Disable2FAView,
    LoginWith2FAView,ForgotPasswordRequestView, ResetPasswordView,GoogleAuthView,
    OperatorOnboardingView, OperatorAccountInfoView, OperatorPersonalInfoView,
    OperatorChangePasswordView, OperatorLogoutView, OperatorOnboardingListView,
    OperatorOnboardingApproveView, OperatorOnboardingRejectView,
    StaffRegistrationView, StaffLoginView,
    AdminLoginView, AdminUserListView, AdminOperatorListView,
    AdminOperatorAdminListView, AdminOnboardingListView,
    AdminUserOnboardingListView, AdminUserOnboardingApproveView, AdminUserOnboardingRejectView
)

urlpatterns = [
    path('registeruser/', UserRegistrationView.as_view(), name='register-user'),
    path('register/', StaffRegistrationView.as_view(), name='register-staff'),
    path('login/', StaffLoginView.as_view(), name='login-staff'),
    path('onboardinguser/', OnboardingView.as_view(), name='onboarding'),
    path('loginuser/', UserLoginView.as_view(), name='login-user'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('accountinfo/', AccountInfoView.as_view(), name='account-info'),
    path('personalinfo/', PersonalInfoView.as_view(), name='personal-info'),
    path('changepassword/', ChangePasswordView.as_view(), name='change-password'),
    path('2fasetup/', Setup2FAView.as_view(), name='2fa-setup'),
    path('2faverify/', Verify2FAView.as_view(), name='2fa-verify'),
    path('2fadisable/', Disable2FAView.as_view(), name='2fa-disable'),
    path('2falogin/', LoginWith2FAView.as_view(), name='2fa-login'),
    path('forgotpassword/', ForgotPasswordRequestView.as_view(), name='forgot-password'),
    path('resetpassword/', ResetPasswordView.as_view(), name='reset-password'),
    path('googleauth/', GoogleAuthView.as_view(), name='google-auth'),
    path('operator/onboarding/', OperatorOnboardingView.as_view(), name='operator-onboarding'),
    path('operator/account-info/', OperatorAccountInfoView.as_view(), name='operator-account-info'),
    path('operator/personal-info/', OperatorPersonalInfoView.as_view(), name='operator-personal-info'),
    path('operator/change-password/', OperatorChangePasswordView.as_view(), name='operator-change-password'),
    path('operator/logout/', OperatorLogoutView.as_view(), name='operator-logout'),
    path('operator/admin/onboardings/', OperatorOnboardingListView.as_view(), name='operator-onboarding-list'),
    path('operator/admin/onboardings/approve/', OperatorOnboardingApproveView.as_view(), name='operator-onboarding-approve'),
    path('operator/admin/onboardings/reject/', OperatorOnboardingRejectView.as_view(), name='operator-onboarding-reject'),
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/users/', AdminUserListView.as_view(), name='admin-users'),
    path('admin/operators/', AdminOperatorListView.as_view(), name='admin-operators'),
    path('admin/operatoradmins/', AdminOperatorAdminListView.as_view(), name='admin-operatoradmins'),
    path('admin/onboardings/', AdminOnboardingListView.as_view(), name='admin-onboardings'),
    path('admin/useronboardings/', AdminUserOnboardingListView.as_view(), name='admin-user-onboardings'),
    path('admin/useronboardings/approve/', AdminUserOnboardingApproveView.as_view(), name='admin-user-onboarding-approve'),
    path('admin/useronboardings/reject/', AdminUserOnboardingRejectView.as_view(), name='admin-user-onboarding-reject'),
]