# Generated by Django 6.0.8 on 2026-08-13 06:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_tax_receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='house_tax_receipt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_card_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pan_card'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rent_agreement',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='rent_agreement'),
        ),
    ]
