# Generated by Django 6.0.8 on 2026-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_house_tax_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ward_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
