# Generated by Django 6.0.8 on 2026-08-13 18:07

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_2fa_enabled_customuser_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('pan_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pan_image')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('aadhaar_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhaar_image')),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_onboardings', to='accounts.operatoradminprofile')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
