# Generated by Django 6.0.8 on 2026-08-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_operatoradminprofile_rename_ward_no_to_panchayath'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
